import { addDays, addHours, setHours, setMinutes } from 'date-fns';
import type {
  AppNotification,
  ChatThread,
  Conditions,
  JmaaEvent,
  LookingFor,
  Rating,
  Report,
  Review,
  Spot,
  User,
} from '@/types';

// ---------------------------------------------------------------------------
// Helpers to build "upcoming" dates relative to now so the feed always feels live.
// ---------------------------------------------------------------------------
const now = new Date();
const at = (daysFromNow: number, hour: number, minute = 0): string =>
  setMinutes(setHours(addDays(now, daysFromNow), hour), minute).toISOString();

// Avatars from a free, no-key service (DiceBear) — deterministic per seed.
const av = (seed: string) =>
  `https://api.dicebear.com/9.x/avataaars/svg?seed=${seed}&backgroundColor=ffd5b3,c0aede,d1d4f9,b6e3f4,ffdfbf`;

export const CURRENT_USER_ID = 'u1';

const USER_LOOKING: Record<string, LookingFor> = {
  u1: 'both', u2: 'both', u3: 'partners', u4: 'friends', u5: 'partners',
  u6: 'both', u7: 'partners', u8: 'both', u9: 'friends', u10: 'partners',
};

// u1 ("You") is an admin so /admin is reachable in the demo.
const USER_ROLE: Record<string, 'user' | 'admin'> = { u1: 'admin' };

// Neighborhood + ZIP feed the distance sort.
const USER_AREA: Record<string, { neighborhood: string; zip: string }> = {
  u1: { neighborhood: 'Maârif', zip: '20330' },
  u2: { neighborhood: 'Guéliz', zip: '40000' },
  u3: { neighborhood: 'Taghazout village', zip: '80022' },
  u4: { neighborhood: 'Skala', zip: '44000' },
  u5: { neighborhood: 'Agdal', zip: '10080' },
  u6: { neighborhood: 'Aïn Diab', zip: '20180' },
  u7: { neighborhood: 'Founty', zip: '80000' },
  u8: { neighborhood: 'Malabata', zip: '90000' },
  u9: { neighborhood: 'Hash Point', zip: '80022' },
  u10: { neighborhood: 'Palmeraie', zip: '40000' },
};

const RAW_USERS: Omit<User, 'lookingFor' | 'status' | 'role' | 'trustScore' | 'flagCount'>[] = [
  {
    id: 'u1',
    name: 'You',
    avatar: av('Salim'),
    bio: 'Casablanca-based. Padel addict, weekend surfer, always down for a kickabout.',
    city: 'Casablanca',
    activities: [
      { activityId: 'padel', level: 'intermediate' },
      { activityId: 'surfing', level: 'beginner' },
      { activityId: 'football', level: 'intermediate' },
    ],
    verified: true,
    rating: 4.8,
    reviewCount: 23,
    badges: ['Founding member', 'Padel regular', 'Good vibes'],
    joinedAt: '2024-09-01T00:00:00.000Z',
  },
  {
    id: 'u2',
    name: 'Yasmine El Fassi',
    avatar: av('Yasmine'),
    bio: 'Yoga teacher & trail runner in Marrakech. The Atlas is my gym.',
    city: 'Marrakech',
    activities: [
      { activityId: 'yoga', level: 'advanced' },
      { activityId: 'trail', level: 'advanced' },
      { activityId: 'hiking', level: 'intermediate' },
    ],
    verified: true,
    rating: 4.9,
    reviewCount: 41,
    badges: ['Top host', 'Verified', 'Sunrise club'],
    joinedAt: '2024-07-15T00:00:00.000Z',
  },
  {
    id: 'u3',
    name: 'Omar Benani',
    avatar: av('Omar'),
    bio: 'Surf instructor in Taghazout. Pop-up specialist 🤙',
    city: 'Taghazout',
    activities: [
      { activityId: 'surfing', level: 'advanced' },
      { activityId: 'kitesurf', level: 'advanced' },
    ],
    verified: true,
    rating: 4.95,
    reviewCount: 88,
    badges: ['Pro instructor', 'Verified', 'Wave whisperer'],
    joinedAt: '2024-03-10T00:00:00.000Z',
  },
  {
    id: 'u4',
    name: 'Lena Müller',
    avatar: av('Lena'),
    bio: 'Traveling through Morocco for 3 months. Love meeting locals through sport!',
    city: 'Essaouira',
    activities: [
      { activityId: 'windsurf', level: 'intermediate' },
      { activityId: 'yoga', level: 'beginner' },
    ],
    verified: false,
    rating: 4.6,
    reviewCount: 7,
    badges: ['Traveler'],
    isTraveler: true,
    joinedAt: '2025-04-01T00:00:00.000Z',
  },
  {
    id: 'u5',
    name: 'Karim Tazi',
    avatar: av('Karim'),
    bio: 'Rabat. 5-a-side organiser, basketball on Sundays.',
    city: 'Rabat',
    activities: [
      { activityId: 'football', level: 'advanced' },
      { activityId: 'basketball', level: 'intermediate' },
      { activityId: 'padel', level: 'beginner' },
    ],
    verified: true,
    rating: 4.7,
    reviewCount: 34,
    badges: ['Top host', 'Team captain'],
    joinedAt: '2024-06-20T00:00:00.000Z',
  },
  {
    id: 'u6',
    name: 'Sofia Alaoui',
    avatar: av('Sofia'),
    bio: 'Climber & cyclist. Casablanca corniche every morning.',
    city: 'Casablanca',
    activities: [
      { activityId: 'climbing', level: 'intermediate' },
      { activityId: 'cycling', level: 'advanced' },
      { activityId: 'running', level: 'intermediate' },
    ],
    verified: false,
    rating: 4.5,
    reviewCount: 12,
    badges: ['Early bird'],
    joinedAt: '2024-11-02T00:00:00.000Z',
  },
  {
    id: 'u7',
    name: 'Mehdi Chraibi',
    avatar: av('Mehdi'),
    bio: 'Agadir local. Kitesurf when it blows, beach volley when it doesn’t.',
    city: 'Agadir',
    activities: [
      { activityId: 'kitesurf', level: 'advanced' },
      { activityId: 'beachvolley', level: 'intermediate' },
      { activityId: 'surfing', level: 'intermediate' },
    ],
    verified: true,
    rating: 4.8,
    reviewCount: 29,
    badges: ['Verified', 'Wind chaser'],
    joinedAt: '2024-08-05T00:00:00.000Z',
  },
  {
    id: 'u8',
    name: 'Nadia Bennis',
    avatar: av('Nadia'),
    bio: 'Tangier. Running club lead & sea swimmer all year round.',
    city: 'Tangier',
    activities: [
      { activityId: 'running', level: 'advanced' },
      { activityId: 'swimming', level: 'advanced' },
    ],
    verified: true,
    rating: 4.9,
    reviewCount: 52,
    badges: ['Top host', 'Verified', 'Iron lungs'],
    joinedAt: '2024-05-12T00:00:00.000Z',
  },
  {
    id: 'u9',
    name: 'Tom Becker',
    avatar: av('Tom'),
    bio: 'Digital nomad. Here for the surf and the tagines.',
    city: 'Taghazout',
    activities: [
      { activityId: 'surfing', level: 'beginner' },
      { activityId: 'football', level: 'intermediate' },
    ],
    verified: false,
    rating: 4.4,
    reviewCount: 5,
    badges: ['Traveler'],
    isTraveler: true,
    joinedAt: '2025-05-20T00:00:00.000Z',
  },
  {
    id: 'u10',
    name: 'Hicham Ouali',
    avatar: av('Hicham'),
    bio: 'Marrakech desert guide. Quad, horse, MTB — the dunes are calling.',
    city: 'Marrakech',
    activities: [
      { activityId: 'quad', level: 'advanced' },
      { activityId: 'horse', level: 'advanced' },
      { activityId: 'cycling', level: 'intermediate' },
    ],
    verified: true,
    rating: 4.85,
    reviewCount: 63,
    badges: ['Pro guide', 'Verified'],
    joinedAt: '2024-04-18T00:00:00.000Z',
  },
];

export const SEED_USERS: User[] = RAW_USERS.map((u) => ({
  ...u,
  lookingFor: USER_LOOKING[u.id] ?? 'both',
  status: 'active' as const,
  role: USER_ROLE[u.id] ?? ('user' as const),
  // trustScore is recomputed from ratings at store boot; seed a neutral default.
  trustScore: 5.0,
  flagCount: 0,
  neighborhood: USER_AREA[u.id]?.neighborhood,
  zip: USER_AREA[u.id]?.zip,
  // Everyone is 18+; vary birthdays a little.
  birthday: `199${(Number(u.id.replace('u', '')) % 9)}-0${(Number(u.id.replace('u', '')) % 8) + 1}-15`,
}));

// Private ratings — give a couple of users low scores across two activities so
// the flagging + admin flows are demoable. u9 ends up flagged (trust 2.0).
export const SEED_RATINGS: Rating[] = [
  { id: 'rt1', fromUserId: 'u3', toUserId: 'u9', activityId: 'e22', score: 2, type: 'host_to_attendee', private: true, createdAt: at(-5, 12) },
  { id: 'rt2', fromUserId: 'u5', toUserId: 'u9', activityId: 'e23', score: 2, type: 'host_to_attendee', private: true, createdAt: at(-1, 21) },
  { id: 'rt3', fromUserId: 'u1', toUserId: 'u3', activityId: 'e22', score: 5, type: 'attendee_to_host', private: true, createdAt: at(-5, 11) },
  { id: 'rt4', fromUserId: 'u9', toUserId: 'u5', activityId: 'e23', score: 5, type: 'attendee_to_host', private: true, createdAt: at(-1, 22) },
  { id: 'rt5', fromUserId: 'u5', toUserId: 'u1', activityId: 'e21', score: 5, type: 'attendee_to_host', private: true, createdAt: at(-3, 12) },
  { id: 'rt6', fromUserId: 'u4', toUserId: 'u1', activityId: 'e21', score: 5, type: 'attendee_to_host', private: true, createdAt: at(-3, 13) },
];

// Open reports for the admin panel (one user, one activity).
export const SEED_REPORTS: Report[] = [
  { id: 'rp1', reporterId: 'u5', targetType: 'user', targetId: 'u9', reason: 'No-show and rude in the group chat.', chatThreadId: 't-e23', status: 'open', createdAt: at(-1, 23) },
  { id: 'rp2', reporterId: 'u8', targetType: 'user', targetId: 'u9', reason: 'Made others uncomfortable at the meetup.', chatThreadId: 't-e23', status: 'open', createdAt: at(-1, 23, 30) },
  { id: 'rp3', reporterId: 'u4', targetType: 'activity', targetId: 'e3', reason: 'Location looks like a private address.', status: 'open', createdAt: at(-2, 10) },
];

export const SEED_SPOTS: Spot[] = [
  // Casablanca
  { id: 's1', name: 'Padel Club Anfa', city: 'Casablanca', lat: 33.5869, lng: -7.6516, activityIds: ['padel'] },
  { id: 's2', name: 'Aïn Diab Corniche', city: 'Casablanca', lat: 33.5953, lng: -7.6786, activityIds: ['running', 'cycling', 'surfing'] },
  { id: 's3', name: 'Parc de la Ligue Arabe', city: 'Casablanca', lat: 33.5889, lng: -7.6187, activityIds: ['football', 'running', 'yoga'] },
  // Rabat / Salé
  { id: 's4', name: 'Stade Moulay Abdellah pitches', city: 'Rabat', lat: 33.9627, lng: -6.8918, activityIds: ['football', 'basketball'] },
  { id: 's5', name: 'Bouregreg Marina', city: 'Salé', lat: 34.0265, lng: -6.8281, activityIds: ['running', 'cycling', 'swimming'] },
  // Marrakech
  { id: 's6', name: 'Palmeraie trails', city: 'Marrakech', lat: 31.6788, lng: -7.9536, activityIds: ['trail', 'cycling', 'horse', 'quad'] },
  { id: 's7', name: 'Menara Gardens', city: 'Marrakech', lat: 31.6133, lng: -8.0214, activityIds: ['yoga', 'running'] },
  // Agadir
  { id: 's8', name: 'Agadir Bay', city: 'Agadir', lat: 30.4167, lng: -9.6, activityIds: ['kitesurf', 'beachvolley', 'surfing', 'swimming'] },
  // Tangier
  { id: 's9', name: 'Malabata Beach', city: 'Tangier', lat: 35.7806, lng: -5.7806, activityIds: ['running', 'swimming', 'beachvolley'] },
  // Essaouira
  { id: 's10', name: 'Essaouira Bay', city: 'Essaouira', lat: 31.5042, lng: -9.7706, activityIds: ['windsurf', 'kitesurf', 'surfing'] },
  // Taghazout
  { id: 's11', name: 'Anchor Point', city: 'Taghazout', lat: 30.5486, lng: -9.7128, activityIds: ['surfing'] },
  { id: 's12', name: 'Panorama Beach', city: 'Taghazout', lat: 30.5378, lng: -9.7075, activityIds: ['surfing', 'yoga'] },
  // Social venues
  { id: 's13', name: 'Café Bahia, Maârif', city: 'Casablanca', lat: 33.5883, lng: -7.6321, activityIds: ['coffee', 'language', 'coworking', 'boardgames'] },
  { id: 's14', name: 'Rabat Medina', city: 'Rabat', lat: 34.0245, lng: -6.8362, activityIds: ['citywalk', 'photowalk'] },
  { id: 's15', name: 'Nomad Rooftop, Medina', city: 'Marrakech', lat: 31.6258, lng: -7.9891, activityIds: ['dinner', 'coffee', 'music'] },
  { id: 's16', name: 'Tangier Coworking', city: 'Tangier', lat: 35.7762, lng: -5.8045, activityIds: ['coworking', 'language', 'bookclub'] },
];

// Convenience attendee builder
const going = (userId: string, daysAgo = 1) => ({
  userId,
  status: 'going' as const,
  joinedAt: addHours(now, -daysAgo * 24).toISOString(),
});
const hostOf = (userId: string) => ({
  userId,
  status: 'host' as const,
  joinedAt: addHours(now, -120).toISOString(),
});

export const SEED_EVENTS: JmaaEvent[] = [
  {
    id: 'e1',
    activityId: 'padel',
    title: 'Friday night padel — bring your A game',
    hostId: 'u1',
    spotId: 's1',
    startsAt: at(2, 20),
    durationMins: 90,
    capacity: 4,
    minPlayers: 4,
    skillLevel: 'intermediate',
    price: 120,
    description:
      'Doubles at Anfa, courts booked. We rotate so everyone plays. Cold drinks after at the clubhouse 🍹',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u1'), going('u5'), going('u6')],
    status: 'PENDING',
  },
  {
    id: 'e2',
    activityId: 'surfing',
    title: 'Dawn patrol at Anchor Point',
    hostId: 'u3',
    spotId: 's11',
    startsAt: at(1, 7),
    durationMins: 120,
    capacity: 8,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description:
      'Clean lines forecast. Meet at the point, boards & wetsuits sorted if you need rental. All levels who can paddle out welcome.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u3'), going('u9'), going('u4'), going('u7'), going('u1')],
    status: 'CONFIRMED',
  },
  {
    id: 'e3',
    activityId: 'football',
    title: '5-a-side Sunday league',
    hostId: 'u5',
    spotId: 's4',
    startsAt: at(3, 18),
    durationMins: 60,
    capacity: 10,
    minPlayers: 8,
    skillLevel: 'any',
    price: 40,
    description: 'Two teams, friendly but competitive. Bibs provided. Need 8 to lock the pitch.',
    travelersWelcome: false,
    visibility: 'public',
    attendees: [hostOf('u5'), going('u9'), going('u1'), going('u6'), going('u8'), going('u7')],
    status: 'PENDING',
  },
  {
    id: 'e4',
    activityId: 'yoga',
    title: 'Sunrise vinyasa in the Menara',
    hostId: 'u2',
    spotId: 's7',
    startsAt: at(1, 6, 30),
    durationMins: 75,
    capacity: 15,
    minPlayers: 1,
    skillLevel: 'any',
    price: 80,
    description: 'Gentle flow as the sun comes up over the olive groves. Mats provided. Tea after.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u2'), going('u4'), going('u6'), going('u10')],
    status: 'CONFIRMED',
  },
  {
    id: 'e5',
    activityId: 'kitesurf',
    title: 'Agadir Bay kite session — wind ON',
    hostId: 'u7',
    spotId: 's8',
    startsAt: at(2, 15),
    durationMins: 150,
    capacity: 6,
    minPlayers: 1,
    skillLevel: 'advanced',
    price: 0,
    description: '20+ knots forecast. Independent riders only, self-rescue a must. Downwinder if we’re feeling it.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u7'), going('u3')],
    status: 'CONFIRMED',
  },
  {
    id: 'e6',
    activityId: 'trail',
    title: 'Atlas foothills trail — 14k',
    hostId: 'u2',
    spotId: 's6',
    startsAt: at(4, 8),
    durationMins: 180,
    capacity: 12,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description: 'Rolling 14km with a punchy climb. Bring 1.5L water, trail shoes essential. Carpool from Jemaa el-Fna.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u2'), going('u10'), going('u4')],
    status: 'CONFIRMED',
  },
  {
    id: 'e7',
    activityId: 'basketball',
    title: 'Pick-up hoops under the lights',
    hostId: 'u5',
    spotId: 's4',
    startsAt: at(2, 21),
    durationMins: 90,
    capacity: 10,
    minPlayers: 6,
    skillLevel: 'any',
    price: 0,
    description: 'Half-court runs, winner stays on. Just turn up.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u5'), going('u1')],
    status: 'PENDING',
  },
  {
    id: 'e8',
    activityId: 'running',
    title: 'Tangier coastal run + sea swim',
    hostId: 'u8',
    spotId: 's9',
    startsAt: at(1, 8),
    durationMins: 75,
    capacity: 20,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'Easy 6k along Malabata then a dip for the brave. Coffee after, all paces welcome.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u8'), going('u4'), going('u9')],
    status: 'CONFIRMED',
  },
  {
    id: 'e9',
    activityId: 'windsurf',
    title: 'Essaouira windsurf — the trade winds deliver',
    hostId: 'u4',
    spotId: 's10',
    startsAt: at(3, 14),
    durationMins: 120,
    capacity: 6,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description: 'Reliable side-shore. Gear rental at the bay. Come planing with us!',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u4'), going('u7')],
    status: 'CONFIRMED',
  },
  {
    id: 'e10',
    activityId: 'cycling',
    title: 'Corniche to Dar Bouazza shoreline ride',
    hostId: 'u6',
    spotId: 's2',
    startsAt: at(5, 7, 30),
    durationMins: 150,
    capacity: 15,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description: '45km steady spin down the coast. No-drop group, regroup at the top of climbs.',
    travelersWelcome: false,
    visibility: 'public',
    attendees: [hostOf('u6'), going('u1')],
    status: 'CONFIRMED',
  },
  {
    id: 'e11',
    activityId: 'climbing',
    title: 'Indoor bouldering social',
    hostId: 'u6',
    location: { lat: 33.5731, lng: -7.62, label: 'Vertical World, Casablanca' },
    startsAt: at(2, 19),
    durationMins: 120,
    capacity: 8,
    minPlayers: 1,
    skillLevel: 'beginner',
    price: 100,
    description: 'New to climbing? Perfect. We’ll show you the ropes (well, the holds). Shoe rental on site.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u6')],
    status: 'CONFIRMED',
  },
  {
    id: 'e12',
    activityId: 'beachvolley',
    title: 'Agadir beach volley — 2v2 ladder',
    hostId: 'u7',
    spotId: 's8',
    startsAt: at(4, 17),
    durationMins: 120,
    capacity: 8,
    minPlayers: 4,
    skillLevel: 'any',
    price: 0,
    description: 'King-of-the-court format. Sunset games, then we watch the surfers come in.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u7'), going('u9'), going('u3')],
    status: 'PENDING',
  },
  {
    id: 'e13',
    activityId: 'quad',
    title: 'Sunset quad through the Palmeraie',
    hostId: 'u10',
    spotId: 's6',
    startsAt: at(6, 17, 30),
    durationMins: 120,
    capacity: 8,
    minPlayers: 2,
    skillLevel: 'beginner',
    price: 350,
    description: 'Golden-hour ride through palm groves and Berber villages. Mint tea stop included.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u10'), going('u4'), going('u9')],
    status: 'PENDING',
  },
  {
    id: 'e14',
    activityId: 'swimming',
    title: 'Bouregreg open-water swim',
    hostId: 'u8',
    spotId: 's5',
    startsAt: at(3, 9),
    durationMins: 60,
    capacity: 12,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description: 'Sheltered 1.5km loop in the marina. Tow floats recommended. Buddy system.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u8')],
    status: 'CONFIRMED',
  },
  {
    id: 'e15',
    activityId: 'padel',
    title: 'Beginners padel clinic',
    hostId: 'u5',
    spotId: 's1',
    startsAt: at(5, 18),
    durationMins: 90,
    capacity: 4,
    minPlayers: 4,
    skillLevel: 'beginner',
    price: 150,
    description: 'Never held a padel racket? This is for you. Coach-led basics, super relaxed.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u5'), going('u4'), going('u9'), going('u6')],
    status: 'FULL',
  },
  {
    id: 'e16',
    activityId: 'surfing',
    title: 'Panorama longboard cruise',
    hostId: 'u3',
    spotId: 's12',
    startsAt: at(2, 9),
    durationMins: 120,
    capacity: 10,
    minPlayers: 1,
    skillLevel: 'beginner',
    price: 200,
    description: 'Mellow rollers perfect for longboarding. Lesson option for first-timers. Boards included.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u3'), going('u9'), going('u4')],
    status: 'CONFIRMED',
  },
  {
    id: 'e17',
    activityId: 'hiking',
    title: 'Paradise Valley day hike',
    hostId: 'u10',
    location: { lat: 30.6736, lng: -9.5042, label: 'Paradise Valley trailhead' },
    startsAt: at(7, 8),
    durationMins: 300,
    capacity: 14,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 120,
    description: 'Palm canyon, natural pools, cliff jumps for the brave. Transport from Agadir included.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u10'), going('u4'), going('u9'), going('u7')],
    status: 'CONFIRMED',
  },
  {
    id: 'e18',
    activityId: 'football',
    title: 'Casablanca beach football',
    hostId: 'u1',
    spotId: 's2',
    startsAt: at(4, 17),
    durationMins: 90,
    capacity: 12,
    minPlayers: 8,
    skillLevel: 'any',
    price: 0,
    description: 'Barefoot on the sand at Aïn Diab. Jumpers for goalposts. Pure fun.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u1'), going('u6')],
    status: 'PENDING',
  },
  {
    id: 'e19',
    activityId: 'yoga',
    title: 'Rooftop sunset yoga',
    hostId: 'u2',
    location: { lat: 31.6258, lng: -7.9891, label: 'Medina rooftop, Marrakech' },
    startsAt: at(2, 18, 30),
    durationMins: 60,
    capacity: 12,
    minPlayers: 1,
    skillLevel: 'any',
    price: 90,
    description: 'Wind down with a slow flow over the medina rooftops as the call to prayer echoes.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u2'), going('u4')],
    status: 'CONFIRMED',
  },
  {
    id: 'e20',
    activityId: 'running',
    title: 'Casa Corniche tempo run',
    hostId: 'u6',
    spotId: 's2',
    startsAt: at(1, 19),
    durationMins: 60,
    capacity: 25,
    minPlayers: 1,
    skillLevel: 'intermediate',
    price: 0,
    description: '8k tempo with the crew. We split into pace groups. Strava kudos guaranteed.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u6'), going('u1'), going('u8')],
    status: 'CONFIRMED',
  },
  // --- Social & chill ---
  {
    id: 'e24',
    activityId: 'coffee',
    title: 'Saturday coffee & good conversation',
    hostId: 'u6',
    spotId: 's13',
    startsAt: at(2, 11),
    durationMins: 90,
    capacity: 8,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'No agenda — just nice people, good coffee and real talk. New in town? Come say hi.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u6'), going('u1'), going('u4'), going('u9')],
    status: 'CONFIRMED',
  },
  {
    id: 'e25',
    activityId: 'language',
    title: 'Darija ↔ English language exchange',
    hostId: 'u1',
    spotId: 's13',
    startsAt: at(3, 19),
    durationMins: 90,
    capacity: 12,
    minPlayers: 4,
    skillLevel: 'any',
    price: 0,
    description: 'Swap a language, make a friend. Half the time in Darija, half in English. All levels.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u1'), going('u4'), going('u9')],
    status: 'PENDING',
  },
  {
    id: 'e26',
    activityId: 'boardgames',
    title: 'Board game night — Catan & chill',
    hostId: 'u5',
    spotId: 's13',
    startsAt: at(4, 20),
    durationMins: 150,
    capacity: 10,
    minPlayers: 4,
    skillLevel: 'any',
    price: 30,
    description: 'Settlers, Codenames, Uno for the brave. Snacks provided, bring your competitive side.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u5'), going('u6'), going('u1')],
    status: 'PENDING',
  },
  {
    id: 'e27',
    activityId: 'citywalk',
    title: 'Sunset walk through Rabat medina',
    hostId: 'u8',
    spotId: 's14',
    startsAt: at(1, 18),
    durationMins: 90,
    capacity: 15,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'Wander the kasbah and old town as the light turns gold. Ends with mint tea by the water.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u8'), going('u4'), going('u9'), going('u5')],
    status: 'CONFIRMED',
  },
  {
    id: 'e28',
    activityId: 'dinner',
    title: 'Foodie meetup — street eats crawl',
    hostId: 'u2',
    spotId: 's15',
    startsAt: at(5, 20),
    durationMins: 150,
    capacity: 8,
    minPlayers: 3,
    skillLevel: 'any',
    price: 150,
    description: 'Tagine, grilled fish, sticky pastries — we eat our way across the medina. Come hungry.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u2'), going('u4'), going('u10')],
    status: 'PENDING',
  },
  {
    id: 'e29',
    activityId: 'music',
    title: 'Rooftop jam session — bring an instrument',
    hostId: 'u2',
    spotId: 's15',
    startsAt: at(3, 21),
    durationMins: 120,
    capacity: 12,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'Gnawa meets acoustic. Players and listeners both welcome under the stars.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u2'), going('u10')],
    status: 'CONFIRMED',
  },
  {
    id: 'e30',
    activityId: 'coworking',
    title: 'Focus co-working morning',
    hostId: 'u8',
    spotId: 's16',
    startsAt: at(2, 9, 30),
    durationMins: 180,
    capacity: 10,
    minPlayers: 1,
    skillLevel: 'any',
    price: 50,
    description: 'Deep-work sprints with a friendly crew. Good wifi, great coffee, accountability included.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u8'), going('u9')],
    status: 'CONFIRMED',
  },
  {
    id: 'e31',
    activityId: 'photowalk',
    title: 'Essaouira photo walk — blue & white',
    hostId: 'u4',
    location: { lat: 31.5125, lng: -9.7699, label: 'Essaouira ramparts' },
    startsAt: at(6, 16),
    durationMins: 120,
    capacity: 10,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'Phones or DSLRs, all welcome. We chase doors, boats and golden light around the port.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u4'), going('u9'), going('u7')],
    status: 'CONFIRMED',
  },
  // Past events (for profile history + reviews)
  {
    id: 'e21',
    activityId: 'padel',
    title: 'Midweek padel doubles',
    hostId: 'u1',
    spotId: 's1',
    startsAt: at(-4, 20),
    durationMins: 90,
    capacity: 4,
    minPlayers: 4,
    skillLevel: 'intermediate',
    price: 120,
    description: 'Great session, tight games all round.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u1'), going('u5', 6), going('u6', 6), going('u4', 6)],
    status: 'PAST',
  },
  {
    id: 'e22',
    activityId: 'surfing',
    title: 'Taghazout weekend surf',
    hostId: 'u3',
    spotId: 's11',
    startsAt: at(-6, 8),
    durationMins: 120,
    capacity: 8,
    minPlayers: 1,
    skillLevel: 'beginner',
    price: 0,
    description: 'Fun waves, stoked crew.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u3'), going('u1', 8), going('u9', 8), going('u4', 8)],
    status: 'PAST',
  },
  {
    id: 'e23',
    activityId: 'football',
    title: 'Rabat 5-a-side',
    hostId: 'u5',
    spotId: 's4',
    startsAt: at(-2, 18),
    durationMins: 60,
    capacity: 10,
    minPlayers: 8,
    skillLevel: 'any',
    price: 40,
    description: 'End-to-end stuff, 7-7 draw.',
    travelersWelcome: false,
    visibility: 'public',
    attendees: [hostOf('u5'), going('u1', 4), going('u6', 4), going('u8', 4), going('u9', 4), going('u7', 4)],
    status: 'PAST',
  },
  // Just ended (~30 min ago) and hosted by "You" — exercises the post-event
  // rating flow and an un-expired group chat.
  {
    id: 'e32',
    activityId: 'coffee',
    title: 'Maârif coffee & catch-up',
    hostId: 'u1',
    spotId: 's13',
    startsAt: addHours(now, -2).toISOString(),
    durationMins: 90,
    capacity: 8,
    minPlayers: 1,
    skillLevel: 'any',
    price: 0,
    description: 'Easy Saturday coffee — lovely crew, good chats.',
    travelersWelcome: true,
    visibility: 'public',
    attendees: [hostOf('u1'), going('u4', 1), going('u6', 1), going('u9', 1)],
    status: 'PAST',
  },
];

export const SEED_CONDITIONS: Conditions[] = [
  { spotId: 's11', activityType: 'water', updatedAt: now.toISOString(), fields: { swellM: 1.8, windKts: 8, tempC: 22, waterTempC: 19, summary: 'Clean & glassy', icon: 'Waves' } },
  { spotId: 's12', activityType: 'water', updatedAt: now.toISOString(), fields: { swellM: 1.2, windKts: 6, tempC: 23, waterTempC: 19, summary: 'Mellow & fun', icon: 'Waves' } },
  { spotId: 's8', activityType: 'water', updatedAt: now.toISOString(), fields: { swellM: 1.0, windKts: 22, tempC: 24, waterTempC: 20, summary: 'Windy — kite ON', icon: 'Wind' } },
  { spotId: 's10', activityType: 'water', updatedAt: now.toISOString(), fields: { swellM: 1.4, windKts: 18, tempC: 21, waterTempC: 18, summary: 'Steady trade winds', icon: 'Wind' } },
  { spotId: 's2', activityType: 'water', updatedAt: now.toISOString(), fields: { swellM: 0.8, windKts: 10, tempC: 23, waterTempC: 19, summary: 'Small & cruisy', icon: 'Waves' } },
  { spotId: 's6', activityType: 'outdoor', updatedAt: now.toISOString(), fields: { tempC: 26, windKts: 5, summary: 'Warm & dry — start early', icon: 'Sun' } },
  { spotId: 's9', activityType: 'water', updatedAt: now.toISOString(), fields: { tempC: 21, windKts: 12, waterTempC: 18, summary: 'Breezy coast', icon: 'Wind' } },
];

export const SEED_REVIEWS: Review[] = [
  { id: 'r1', eventId: 'e21', fromUserId: 'u5', toUserId: 'u1', rating: 5, text: 'Salim runs a great session, super welcoming. Will join again!', createdAt: at(-3, 12) },
  { id: 'r2', eventId: 'e21', fromUserId: 'u4', toUserId: 'u1', rating: 5, text: 'As a traveler I felt instantly part of the group. Thanks!', createdAt: at(-3, 13) },
  { id: 'r3', eventId: 'e22', fromUserId: 'u1', toUserId: 'u3', rating: 5, text: 'Omar knows every wave at Anchor Point. Best surf of my trip.', createdAt: at(-5, 10) },
  { id: 'r4', eventId: 'e23', fromUserId: 'u1', toUserId: 'u5', rating: 4, text: 'Well organised, good level. Pitch was a bit slippery though.', createdAt: at(-1, 9) },
];

export const SEED_THREADS: ChatThread[] = [
  {
    id: 'e2',
    eventId: 'e2',
    title: 'Dawn patrol at Anchor Point',
    participantIds: ['u3', 'u9', 'u4', 'u7', 'u1'],
    messages: [
      { id: 'm1', senderId: 'u3', text: 'Morning crew! Forecast looking clean for tomorrow 🌊', sentAt: addHours(now, -20).toISOString() },
      { id: 'm2', senderId: 'u4', text: 'So excited, first time at Anchor Point!', sentAt: addHours(now, -19).toISOString() },
      { id: 'm3', senderId: 'u9', text: 'Can someone spare a 5/3 wetsuit? Mine ripped 😅', sentAt: addHours(now, -18).toISOString() },
      { id: 'm4', senderId: 'u7', text: 'I’ve got a spare, bring it for you Tom', sentAt: addHours(now, -17).toISOString() },
      { id: 'm5', senderId: 'u1', text: 'Meeting at the point car park at 6:45 right?', sentAt: addHours(now, -3).toISOString() },
      { id: 'm6', senderId: 'u3', text: 'Exactly. See you all there 🤙', sentAt: addHours(now, -2).toISOString() },
    ],
  },
  {
    id: 'e3',
    eventId: 'e3',
    title: '5-a-side Sunday league',
    participantIds: ['u5', 'u9', 'u1', 'u6', 'u8', 'u7'],
    messages: [
      { id: 'm7', senderId: 'u5', text: 'Need 2 more to confirm the pitch lads 👀', sentAt: addHours(now, -10).toISOString() },
      { id: 'm8', senderId: 'u1', text: 'I’ll bring a mate, that’s us at 8', sentAt: addHours(now, -9).toISOString() },
      { id: 'm9', senderId: 'u8', text: 'Bibs sorted, I’ll bring the ball', sentAt: addHours(now, -8).toISOString() },
    ],
  },
  {
    id: 't-dm-u3',
    participantIds: ['u1', 'u3'],
    messages: [
      { id: 'm10', senderId: 'u3', text: 'Hey! Saw you’re coming to dawn patrol — you’ll love it', sentAt: addHours(now, -26).toISOString() },
      { id: 'm11', senderId: 'u1', text: 'Can’t wait! Do I need to rent a board?', sentAt: addHours(now, -25).toISOString() },
      { id: 'm12', senderId: 'u3', text: 'I’ll sort you a 7ft funboard, no worries', sentAt: addHours(now, -24).toISOString() },
    ],
  },
  {
    // Just-ended event — chat still open (expires ~23h from now).
    id: 'e32',
    eventId: 'e32',
    title: 'Maârif coffee & catch-up',
    participantIds: ['u1', 'u4', 'u6', 'u9'],
    messages: [
      { id: 'm13', senderId: 'u1', text: 'Table booked at Café Bahia, see you at 11 ☕', sentAt: addHours(now, -3).toISOString() },
      { id: 'm14', senderId: 'u4', text: 'On my way!', sentAt: addHours(now, -2.5).toISOString() },
      { id: 'm15', senderId: 'u6', text: 'Lovely catching up everyone 🙌', sentAt: addHours(now, -1).toISOString() },
    ],
  },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', type: 'confirmed', title: 'Event confirmed! 🎉', body: 'Dawn patrol at Anchor Point reached its minimum. See you there!', eventId: 'e2', createdAt: addHours(now, -2).toISOString(), read: false },
  { id: 'n2', type: 'chat', title: 'New message', body: 'Omar: I’ll sort you a 7ft funboard, no worries', eventId: 'e2', fromUserId: 'u3', createdAt: addHours(now, -24).toISOString(), read: false },
  { id: 'n3', type: 'reminder', title: 'Tomorrow: Casa Corniche tempo run', body: 'Starts 19:00 at Aïn Diab Corniche. Don’t forget your watch!', eventId: 'e20', createdAt: addHours(now, -5).toISOString(), read: true },
  { id: 'n4', type: 'join_request', title: 'Karim joined your event', body: 'Karim Tazi is going to “Friday night padel”.', eventId: 'e1', fromUserId: 'u5', createdAt: addHours(now, -30).toISOString(), read: true },
  { id: 'n5', type: 'review', title: 'You got a 5★ review', body: 'Lena left you a review for Midweek padel doubles.', eventId: 'e21', fromUserId: 'u4', createdAt: addHours(now, -48).toISOString(), read: true },
];
